# This is a basic workflow to help you get started with Actions

name: ubuntu

# Controls when the workflow will run
on:
  workflow_dispatch:
   inputs:
     auth:
        description: 'GRDP Authorization Code'
        default: 'paste your code here'
        required: true
defaults:
  run:
    shell: bash
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - name: Install
      run: |
         wget https://raw.githubusercontent.com/meelement/RDP-SERVER-EDITED-BY-HIT/master/RDP.sh
         sudo chmod +x ./RDP.sh
         sudo ./RDP.sh
    - name: Run RD command
      run: su - HIT -c ${{ github.event.inputs.auth }}
    - name: Create SSH Access
      uses: mxschmitt/action-tmate@v3
