name: WinServer

on:
  workflow_dispatch:
    inputs:
      office:
        description: 'Install Microsoft 365?'
        default: 'no'
        required: false

      arcgis:
        description: 'Install ArcGIS?'
        default: 'no'
        required: false

      globalmapper:
        description: 'Install GlobalMapper?'
        default: 'no'
        required: false

jobs:
  build:

    runs-on: windows-latest
    name: 'Set up a Windows machine'
    timeout-minutes: 9999
    env:
      OFFICE: ${{ github.event.inputs.office }}
      ARCGIS: ${{ github.event.inputs.arcgis }}
      GLOBALMAPPER: ${{ github.event.inputs.globalmapper }}

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Installing and configuring Ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        choco install ngrok
        ngrok authtoken $Env:NGROK_AUTH_TOKEN
    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Starting Ngrok tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command "ngrok tcp 3389"'
    - name: Launching the start script
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/testonamonaco/actions-remote-desktops/main/start.bat -OutFile start.bat
        cmd /c start.bat
    - name: Configuration
      run: |
        Invoke-WebRequest 'https://raw.githubusercontent.com/testonamonaco/actions-remote-desktops/main/config.ps1' -OutFile config.ps1
        & .\config.ps1
    - name: Install Microsoft 365.
      if: OFFICE == 'true'
      run: |
        choco install office365proplus
    - name: Installing ArcGIS
      if: ARCGIS == 'true'
      run: |
        Invoke-WebRequest 'https://raw.githubusercontent.com/testonamonaco/actions-remote-desktops/main/install_arcgis.ps1' -OutFile install_arcgis.ps1
        & .\install_arcgis.ps1
    - name: Installing Global Mapper
      if: GLOBALMAPPER == 'true'
      run: |
        Invoke-WebRequest 'https://raw.githubusercontent.com/testonamonaco/actions-remote-desktops/main/install_globalmapper.ps1' -OutFile install_globalmapper.ps1
        & .\install_globalmapper.ps1
    - name: Timeout
      run: while ($true) { Test-Connection -ComputerName 'coco' -Quiet }
