name: Windows Server 2022 Remote Virtual Machine
on:
  workflow_dispatch:
    inputs:
      office:
        description: 'Install Microsoft 365?'
        default: false
        required: false
        type: boolean

      qgis:
        description: 'Install QGIS?'
        default: false
        required: false
        type: boolean

      arcgis:
        description: 'Install ArcGIS?'
        default: false
        required: false
        type: boolean

      globalmapper:
        description: 'Install GlobalMapper?'
        default: false
        required: false
        type: boolean

jobs:
  build:

    runs-on: windows-latest
    name: 'Set up a Windows VM'
    timeout-minutes: 9999

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      env:
        COLLAPSED: false
    - name: Installing and configuring Ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        COLLAPSED: false
      run: |
        choco install ngrok | Out-Null
        ngrok authtoken $Env:NGROK_AUTH_TOKEN

    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      env:
        COLLAPSED: false
    - name: Starting Ngrok tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command "ngrok tcp 3389"'
      env:
        COLLAPSED: false

    - name: Launching the start script
      run: |
        Invoke-Expression (Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/testonamonaco/actions-remote-desktops/main/start.bat').Content

    - name: Configuration
      run: |
        Invoke-Expression (Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/testonamonaco/actions-remote-desktops/main/config.ps1').Content
      env:
        COLLAPSED: false

    - name: Install Microsoft 365.
      if: ${{ github.event.inputs.office == true }}
      run: |
        choco install office365proplus | Out-Null
      env:
        COLLAPSED: false

    - name: Install QGIS.
      if: ${{ github.event.inputs.qgis == true }}
      run: |
        choco install qgis | Out-Null
      env:
        COLLAPSED: false
    - name: Installing ArcGIS
      if: ${{ github.event.inputs.arcgis == true }}
      run: |
        Invoke-Expression (Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/testonamonaco/actions-remote-desktops/main/install_arcgis.ps1').Content
      env:
        COLLAPSED: false
    - name: Installing Global Mapper
      if: ${{ github.event.inputs.globalmapper == true }}
      run: |
        Invoke-Expression (Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/testonamonaco/actions-remote-desktops/main/install_globalmapper.ps1').Content
      env:
        COLLAPSED: false
    - name: Setup TMATE session
      uses: mxschmitt/action-tmate@v3
      env:
        COLLAPSED: false