name: WinServer

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 10

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Installing and configuring Ngrok
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        choco install ngrok
        ngrok authtoken $Env:NGROK_AUTH_TOKEN
    - name: Setting Bing Wallpaper
      run: |
        irm "bing.com$((irm "bing.com/HPImageArchive.aspx?format=js&mkt=en-IN&n=1").images[0].url)" -OutFile D:\a\bingwallpaper.jpg
        reg add "HKEY_CURRENT_USER\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d D:\a\bingwallpaper.jpg /f
        rundll32.exe user32.dll,UpdatePerUserSystemParameters
        taskkill /f /im explorer.exe
        start explorer.exe
    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Starting Ngrok tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command "ngrok tcp 3389"'
    - name: Launching the start script
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/testonamonaco/actions-remote-desktops/main/start.bat -OutFile start.bat
        cmd /c start.bat
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: RDP is ready!
      run: | 
        Invoke-WebRequest https://github.com/testonamonaco/actions-remote-desktops/raw/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
